### ISSUE TITLE
第二周课程答疑整理

### ISSUE THREAD

**Issue by arvinxx** [SubstrateOrg/Team1#15]
第二周课程答疑记录

作业参考思路：

我review了这两天大家在群里的说法，感觉目前比较好的做法是用 `random_seed` ,` nounce`，`sender`三个内容拼起来再用sr_io::blake2_128方法进行hash，得到[u8; 16]，最后用bytecodes的 read方法转成u128。 大家都是怎么考虑的？

其中random_seed代表来自区块的随机信息，sender代表了用户的信息，nounce感觉没啥大用，虽然说可以每次生成后都自增一下，但是下次调用时应该已经不是相同的区块高度了，那个random_seed应该已经不同了，不需要再用nounce来进行区别吧

**Comment by arvinxx** [comment]
>多节点连接设置的—bootnodes=multiaddr，是不是先确保节点加入网络，后续的p2p节点通信与这个设置无关？

也不是完全无关吧，但是就没那么必要了，本地会保存上次从网络上得到的其他节点地址

**Comment by arvinxx** [comment]
>—pruning mode具体是在什么阶段进行数据裁剪呢？

会在新块被确认后

**Comment by arvinxx** [comment]
>  作业的ERC20例子，有关外部函数，是不是需要增加额外的参数 `tokenId？=>` 引申的问题，substrate的合约与以太坊Solidity的合约有对比的文章可以参考么？substrate合约为什么不能作为instance部署呢？

对。可以参考srml-assets。我没有看到类似的文章。runtime module是支持多个instance的，但和你想要的效果不一样。这个完全是架构的问题，比如libra module的选择就和substrate module类似

用ink开发的智能合约的话架构就和以太坊的合约非常类似了。不过ink1.0全是坑，2.0才刚刚开始，所以我不太愿意讲太多ink。

**Comment by arvinxx** [comment]
>目前对substrate module理解还不是很深入￼，就是一链一应用的感觉？ink是pairty搞的么，为啥要有这两种开发合约的架构呀￼

runtime module是链的本身，就好比你想给evm加个byte code，这个级别的。ink就是类似solidity的合约

**Comment by arvinxx** [comment]
> use byteorder::{ByteOrder, LittleEndian}; 引发的问题
![image](https://user-images.githubusercontent.com/28616219/65228848-c9478780-dafd-11e9-8214-eafb6a514935.png)

用的库必须支持 no_std,应该`cargo.toml`加个`default-features = false`

**Comment by arvinxx** [comment]
> 库的使用文档在哪看？

https://crates.parity.io/srml_system/trait.Trait.html#associatedtype.Hash

https://crates.parity.io/substrate_service/index.html 看一下这个是不是你需要的

**Comment by arvinxx** [comment]
总结下，hash可以通过asref转成u8 array（这里感谢@博皞(木头)-扑街写手-上海 提供的信息），然后bytecodes有read方法可以将u8 array转成u128，亲测可用

https://substrate.dev/rustdocs/v1.0/sr_io/fn.blake2_128.html
```rust
use runtime_io::blake2_128;

**Comment by arvinxx** [comment]
> 随机数搞不定了，不知道怎么搞￼？

 作业让设计dna算法，按我的理解，重点应该是设计随机数使用哪些不可控因子，而不纠结怎么生成怎么转换?

取时间戳，对一个素数求模

参考这个也可以 https://www.shawntabrizi.com/substrate-collectables-workshop/#/zh-cn/2/generating-random-data

**Comment by arvinxx** [comment]
> 请教下Decode和Encode现在在哪个module里面，parity_codec出错？

![image](https://user-images.githubusercontent.com/28616219/65375783-cac6aa80-dccb-11e9-85c4-f4b42326d281.png)

```rust
use codec::{Encode, Decode};
```

**Comment by arvinxx** [comment]
> 请问前端查到的数据看不到具体内容，是<unknown>，是什么原因？

![image](https://user-images.githubusercontent.com/28616219/65375799-fc3f7600-dccb-11e9-90fb-b8908cdff1d2.png)

类型不支持，不知道要怎么给你显示。在 setting 里面配置类型

**Comment by arvinxx** [comment]
> 关于在runtime中使用第三方crate的问题，现在已知的限制条件是不能引用rust的std库是吧，那如何知道一个第三方库是否在内部引用了std呢，比如https://github.com/rust-random/rand， 这个rand库，能否用在runtime中

rand是支持的，不过我之前遇到过个坑，现在不知道修好了没，当时我改成master版本才能用

https://crates.io/crates/rand 可以看到Categories有个 No standard library

好像没有个太通用的方法。我都是看库的cargo.toml，一般有no_std feature或者std feature的就是支持的

**Comment by arvinxx** [comment]
我之前有个substrate1.0的代码目录结构介绍


请问是这个吗？ https://mp.weixin.qq.com/s?__biz=MzA5NTQyNDIyNw==&mid=2247483793&idx=1&sn=12e39b66841b4e8b454209a33d1480c7

**Comment by arvinxx** [comment]
>请教大家，substrate支持遍历list么? decl_storage不支持写array？

不支持，但通过map可以模拟出数组。

**Comment by arvinxx** [comment]
问一个cargo的问题， runtime目录下文件修改后是在runtime目录下执行cargo build是吧？

不是，在目录下。先 `cargo check` 再 build

**Comment by arvinxx** [comment]
> 你们是怎么设计一个账户下对应多只猫的？

https://substrate.dev/substrate-collectables-workshop/#/zh-cn/2/owning-multiple-kitties

**Comment by arvinxx** [comment]
> 新建的node里除了template和mymodule之外， 其他的模块比如balance在哪里找到代码？
![image](https://user-images.githubusercontent.com/28616219/65375940-0e6de400-dccd-11e9-912f-82e6d5442cd8.png)


srml下有个balance和其他mod。你看下这个runtime架构，https://mp.weixin.qq.com/s/OUh9-q_P3WdkaLzpvY2P2Q

**Comment by arvinxx** [comment]
> extrinsic怎么拿到hash?
![image](https://user-images.githubusercontent.com/28616219/65375957-2d6c7600-dccd-11e9-8fef-49e11dc5a24e.png)

需要自己encode后blake2_256算

**Comment by arvinxx** [comment]
> substrate 2.0里balances中对任意交易的TakeFees计算有三部分组成，分别为
1.通过extrinsic的bytes len fee
2.和extrinsic的weight有关，而且会乘以上个区块weight相关系数的weight fee
3.tip，额外小费，通常为0

> 现在的问题是：
整个TakeFees完成扣费的过程中没有任何Event发出，导致前端只能预估fee
第一部分我可以准确预估，但第二部分如何预估呀?..

> 还有就是为啥官方没有将这个Fee的真实消耗用Event发出，理由可能是什么呢？
我都想改了pull request去...

**Comment by arvinxx** [comment]
> 我有个问题 实现一个加密猫的 runtime 和一个加密猫的智能合约，有什么区别？我还没分清楚

这个就是runtime module和smart contract的区别。runtime module可以称为系统及的合约，smart contract是用户级的。系统级的就是类似于操作系统的一部分。有着很大的权限，比如可以随意修改用户余额。所以这个升级比如通过治理模块来完成。用户级的合约就和solidity的合约类似，只能修改自己管理的数据。和在操作系统上跑的app类似，可以调用操作系统的功能，但是操作系统会做权限管理

**Comment by arvinxx** [comment]
> 我看有关substrate上有关erc20的例子里token变量是全局共用的，a token 和b token没有隔离的概念吗

以runtime module的方式实现的话，没有，通过smart contract方法实现的话，和solidity的erc20基本一样

> 那我就一个token建一个全局变量？不同的token本质上行为应该不同，所以就刻意分开建总可以吧？

**Comment by arvinxx** [comment]
> 问个问题：这里所说的账户关联的storage被清理掉是指将用户状态数据彻底删除还是什么
![image](https://user-images.githubusercontent.com/28616219/65376069-2b56e700-dcce-11e9-8885-bdf5fa904ad7.png)

就和以太坊只能合约self destruct一样，所有数据包括代码自己全部清除

**Comment by arvinxx** [comment]
> 老师，还有个小问题，上次讲课视频您提了一下transaction里有个longevity的作用，听的不是很明白，🙏

transaction有两种，mortal和immortal，有时效性的和永久有效的

**Comment by arvinxx** [comment]
> 非pow共识都在一定程度会存在可控制交易打包顺序的问题吧

这个问题是不可能避免的，不可能区分是出块节点故意延迟交易，还是他真没收到这比交易

**Comment by arvinxx** [comment]
> 怎么对block_number取余

最简单的就是try_into u128

**Comment by readlnh** [comment]
所以交易的费用是不可避免的吗
